name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
    build:
      name: Build
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v1
        - name: InvokeBuild
          run: Install-Module InvokeBuild -Scope CurrentUser -Force
          shell: powershell
        - name: Build
          run: Invoke-Build
          shell: powershell
        - uses: actions/upload-artifact@v3
          with:
            name: vsix
            path: kit/*.vsix